[package]
name = "rust-eureka"
version = "0.1.0"
authors = ["Jack Wright <jack.wright@nike.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
url = "1.5.1"
log = "0.3.8"
option-filter = "1.0.1"

serde = "1.0"
serde_json = "1.0"

